services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - lutnita-network
    volumes:
      - mongo-data:/data/db

  lutnita-app:
    build: .
    ports:
      - "9000:3000"
    networks:
      - lutnita-network
    depends_on:
      - mongodb

networks:
  lutnita-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local