services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
    networks:
      - lutnita-network
    volumes:
      - mongo-data:/data/db

  lutnita-app:
    build: ./webapp
    ports:
      - "9000:3000"
    networks:
      - lutnita-network
    depends_on:
      - mongodb

  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    networks:
      - lutnita-network

networks:
  lutnita-network:
    driver: bridge

volumes:
  mongo-data:
    driver: local
